### ISSUE TITLE
Suggestion of optimization

### ISSUE THREAD

**Issue by gmpassos** [Mehmetyaz/binary_tree#4]
Check if an element is `identical` before other operations can improve comparison of complex objects, constant instances and `String` objects.

https://github.com/Mehmetyaz/binary_tree/blob/1dea57984cd7524c2ca243d535ff41297e9681b0/lib/src/node.dart#L36

**Comment by Mehmetyaz** [comment]
done! https://github.com/Mehmetyaz/binary_tree/commit/120d1bc1caff76e6223cd8a97c8d961eb97e696d

**Comment by gmpassos** [comment]
Actually you shouldn't replace '=='. You just need to check for identical before, and only if it fails check for '=='.

Use only 'identical' can break a lot of already existing code using this package.

**Comment by Mehmetyaz** [comment]
I did test, all tests passed. But I may not have written some necessary tests.  In which cases should there be a mistake?

**Comment by gmpassos** [comment]
Try with a personalized class that implements `==`  and `hashCode`.

Then try to perform operations with an instance that is not present in the collection.

Using `identical` contains will work only for the exact instance, and not with an equals instance.

**Comment by Mehmetyaz** [comment]
I understand now. So I should use `if(identical || ==)`. Thank you for suggesting. I discovered another detail thanks to you 😊

**Comment by gmpassos** [comment]
But I recommend to make some benchmarks checking if it really improves performance.

Many similar algorithms, like comparators, does this to optimize, but is important to double check.
