### ISSUE TITLE
Wrong expectation about the result of `Comparable.compareTo()`

### ISSUE THREAD

**Issue by Blimster** [Mehmetyaz/binary_tree#6]
Hi,

in the extension `ComparisonOperators` it is expected that the result of `Comparable.compareTo()` is always `-1`, `0` or `1`. But the documentation of `Comparable.compareTo()` only says that the result must be negative, zero or positive.

In my opinion, the implementation of `ComparisonOperators` should look like this.

```dart
extension ComparisonOperators on Comparable {
  bool operator >(Object other) => compareTo(other) > 0;
  bool operator <(Object other) => compareTo(other) < 0;
  bool operator <=(Object other) => compareTo(other) <= 0;
  bool operator >=(Object other) => compareTo(other) >= 0;
}
```

Btw, your package helps me lot the solve some performance issues in my current project! Thanks a lot! ❤️

**Comment by Blimster** [comment]
Just saw, that @kevmoo fixed this about 2 years ago in commit 707aab4. Its time for a new release 😉.

**Comment by kevmoo** [comment]
😆 😆 😆

**Comment by Mehmetyaz** [comment]
:D Sorry. https://pub.dev/packages/binary_tree
